### ISSUE TITLE
Disable string parsing in Request object constructor

### ISSUE THREAD

**Issue by samlovescoding** [rupinder-developer/PHPRoutingFramework#1]
_[PERFORMANCE IMPROVEMENT]_
Constructor of Request class can be converted to a normal function as it will allow the developers to parse the input raw data if he/she has the resources.

**File**: /app/core/request.php

**Comment by rupinder-developer** [comment]
Thanks for reporting an issue. Now you have to call $this->req->parseJSON() & $this->req->parseUrlencoded() methods in your Router class for parsing data. Please checkout the documentation for the same @ https://github.com/rupinder-developer/Tinge-Framework#how-to-accept-http-request-body
