### ISSUE TITLE
PDO MySQL Connector error for PHP>5.3 with MySQL8

### ISSUE THREAD

**Issue by samlovescoding** [rupinder-developer/PHPRoutingFramework#2]
Fatal error: Uncaught PDOException: PDO::__construct(): The server requested authentication method unknown to the client [caching_sha2_password] in C:\xampp\htdocs\xxxxxxxxx\api\app\core\database.php:28 Stack trace: #0 C:\xampp\htdocs\xxxxxxxxx\api\app\core\database.php(28): PDO->__construct('mysql:host=loca...', 'sampanlocal', '12345678') #1 C:\xampp\htdocs\xxxxxxxxx\api\app\models\User.php(5): MySQL\Database->connect() #2 C:\xampp\htdocs\xxxxxxxxx\api\app\routes\Home.php(5): User->create(............) #3 C:\xampp\htdocs\xxxxxxxxx\api\app\core\app.php(48): Home->newuser() #4 C:\xampp\htdocs\xxxxxxxxx\api\index.php(8): App->__construct() #5 {main} Next PDOException: SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client in C:\xampp\htdocs\xxxxxxxxx\api\app\core\database.php:28 Stack trace: #0 C:\xampp\htdocs\xxxxxxxxx\api\app\core\database in C:\xampp\htdocs\xxxxxxxxx\api\app\core\database.php on line 28

**Comment by rupinder-developer** [comment]
Please try to change MySQL port i.e. 3306
